catalog:
  '@astrojs/check': ^0.9.4
  '@astrojs/node': ^9.1.2
  '@types/node': ^22.0.0
  astro: ^5.5
  astro-integration-kit: ^0.18
  sharp: ^0.34.0
  typescript: ^5.7
  vite: ^6.2.6

catalogs:
  min:
    astro: ^5.5
    vite: ^6.2.0

packages:
  - "packages/*"
  - "packages/*/tests/fixtures/*"
  - "playground"
