catalog:
  "@astrojs/node": 10.0.0
  "@types/node": ^22.0.0
  astro: 6.0.0
  sharp: ^0.34.0
  tsdown: ^0.21.0
  typescript: ^5.9.3

packages:
  - "packages/*"
  - "packages/*/tests/fixtures/*"
  - "playground"

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - astro
  - jsr
  - pkg-pr-new
  - studiocms
  - "@studiocms/*"
  - "@withstudiocms/*"
  - "@astrojs/*"

onlyBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
  - sharp
