catalog:
  "@astrojs/node": ^9.5.1
  "@types/node": ^22.0.0
  astro: ^5.16.6
  sharp: ^0.34.0
  typescript: ^5.9.3

packages:
  - "packages/*"
  - "packages/*/tests/fixtures/*"
  - "playground"

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - studiocms
  - "@studiocms/*"
  - "@withstudiocms/*"

onlyBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
  - sharp
