name: CI - Tests PRs & Main

on:
  workflow_dispatch:
  push:
    paths:
      - "packages/**"
      - "vitest.config.mts"
    branches: [main]
  pull_request:
    paths:
      - "packages/**"
      - "vitest.config.mts"
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: testing-${{ github.ref }}

jobs:
  typecheck:
    name: Type Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cmd: ["cfetch"]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run ${{ matrix.cmd }} TypeCheck
        uses: ./.github/actions/type-check
        with:
          cmd: ${{ matrix.cmd }}

  effect-check:
    name: Effect Diagnostics
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cmd: ["cfetch"]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run ${{ matrix.cmd }} Effect Diagnostics
        uses: ./.github/actions/effect-check
        with:
          cmd: ${{ matrix.cmd }}

  jsr-dry-run:
    name: Test JSR Publish
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Check out code using Git
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@main

      - name: Build package
        run: pnpm build

      - name: Test run
        run: pnpm jsr:test

  vitest-reporter:
    name: Run Vitest Tests
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Check out code using Git
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@main

      - name: Build package
        run: pnpm build

      - name: Run Vitest Tests
        run: pnpm ci:test

      - name: Upload HTML report
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: vitest-report
          path: html
          retention-days: 14
